[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
 [[redirects]]
  from = "/sales"
  to = "https://dan.com/buy-domain/seefco.com"
  status = 200
  force = false
